### ISSUE TITLE
What is difference between this repository and EasyMicroservices/Laboratory

### ISSUE THREAD

**Issue by alighodrati** [EasyMicroservices/Network#1]

**Comment by Ali-YousefiTelori** [comment]
Hi @alighodrati .
The laboratory is about mocking.
And Network is about HttpClient, you know we don't have HttpClient in old dotnet or some methods in HttpClient.
We have to make an interface to implement HttpClient, WebRequest, WebClient, etc.
The laboratory has to use this package instead of direct HttpClient.

**Comment by alighodrati** [comment]
Thanks @Ali-YousefiTelori
